import { Metadata } from 'next';

export const sitemetadata: Metadata = {
  title: 'Workspace',
  description: 'Generated by create next app',
  generator: 'Next.js',
  applicationName: 'Next.js',
  referrer: 'origin-when-cross-origin',
  keywords: ['Next', 'React', 'Javascript', 'Typescript'],
  colorScheme: 'dark',
};
